### ISSUE TITLE
Pose order

### ISSUE THREAD

**Issue by edmc2** [duckietown/lib-dt-apriltags#11]
Hellp

This is not an issue as such, but the order of the pose returned is causing me some confusion in implementation.

Is the order for the pose returned by your code (pose_R and pose_t) identical to the order of the pose returned by AprilRobotics ?

My understanding is that the AprilRobotics code returns an estimate of the pose of the camera relative to the tag and, as such, this transformation will map a coordinate vector from the frame of the camera to the frame of the tag.

Many thanks for any help you can offer.

**Comment by AleksandarPetrov** [comment]
@edmc2, as you can see from here:
https://github.com/duckietown/lib-dt-apriltags/blob/48313c7f329af85240a00723803a1c37e13652a1/dt_apriltags/apriltags.py#L385-L392
we directly return the `pose_R` and `pose_t` from the original library without changing them. So the meaning of these variable matches the one in the original [apriltag](https://github.com/AprilRobotics/apriltag) library.

**Comment by edmc2** [comment]
Many thanks for your confirmation Aleksander.
Best Regards,
Ed
