### ISSUE TITLE
Segmentation Fault (PI4, Python 3.7.3)

### ISSUE THREAD

**Issue by aaronglennshepherd** [duckietown/lib-dt-apriltags#17]
Receivingsegmetnation fault in the "at_detector" porion of code.

Pi4
Python 3.7.3

Segfault appearing in this portion of code:
    at_detector = Detector(families='tag36h11',
                  nthreads=2,
                  quad_decimate=1.0,
                  quad_sigma=0.0,
                  refine_edges=1,
                  decode_sharpening=0.25,
                  debug=0)

Appears to be slightly more stable when nthreads=2 (skips my image if all tags are detected) and crashes if nthreads=1. Runs fine on windows 10.

Thanks,
Aaron

**Comment by afdaniele** [comment]
It looks like you are using a different library, this repository is for `dt_apriltags`, you are using `pupil_apriltags` instead for which we are not the maintainers. 
Closing the issue.
