### ISSUE TITLE
Can't install with pip

### ISSUE THREAD

**Issue by ama542blake** [duckietown/lib-dt-apriltags#19]
I have directly copied the pip install command on the readme page (and have simply changed it to pip3 instead of pip). When I run this:
` pip3 install dt-apriltags`

I receive this error:
```ERROR: Could not find a version that satisfies the requirement dt-apriltags (from versions: none)
ERROR: No matching distribution found for dt-apriltags```

Is this library no longer available through pip?

**Comment by Naughty-Monkey** [comment]
I met the same problem

**Comment by hakanErgin** [comment]
Hi. I'm not experienced with the package but I tried installing it on windows environment andnit didn't work. Now I tried on Linux, it seems to install without problems.

It's better if you provide a little more information on your environment. Are you on windows by any chance?

**Comment by Naughty-Monkey** [comment]
MacOS 10.14.6 2.3 GHz Intel Core i5, python3.9

**Comment by hakanErgin** [comment]
> MacOS 10.14.6 2.3 GHz Intel Core i5, python3.9

I have no idea, Sorry
Perhaps try Linux (maybe docker)

**Comment by lukerob01** [comment]
I'm having the same issue (MacOS 11.6, pip 21.3.1, python 3.9)

**Comment by afdaniele** [comment]
The python package comes with a binary embedded, so unfortunately it is not very portable and we are currently not building binaries for Windows or MacOS. Feel free to build for your OS by adapting the build script https://github.com/duckietown/lib-dt-apriltags/blob/master/assets/build.sh.

**Comment by gggdttt** [comment]
> Hi. I'm not experienced with the package but I tried installing it on windows environment andnit didn't work. Now I tried on Linux, it seems to install without problems.
> 
> It's better if you provide a little more information on your environment. Are you on windows by any chance?

Hi, so we can not use it on windows right?

**Comment by hakanErgin** [comment]
> > Hi. I'm not experienced with the package but I tried installing it on windows environment andnit didn't work. Now I tried on Linux, it seems to install without problems.
> > It's better if you provide a little more information on your environment. Are you on windows by any chance?
> 
> Hi, so we can not use it on windows right?

I used it thanks to WSL in windows 10

**Comment by andrewadare** [comment]
Here's a workaround for MacOS users.

  1. Clone this repo with `--recursive` to get the apriltag submodule.
  2. Build libapriltag.dylib.
  3. Copy it to dt_apriltags/ or provide its location to `dt_apriltags.Detector` with the `searchpath` keyword arg.
  4. Use dt_apriltags/apriltags.py as an unpackaged module.
  ```python
  sys.path.append("/path/to/lib-dt-apriltags/dt_apriltags")  # or use PYTHONPATH env variable
  import apriltags as dt_apriltags
  ```
