### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by xmba15** [duckietown/lib-dt-apriltags#20]
Hi @afdaniele, I just saw your recent commits and thought you are the current maintainer for this library. Sorry if that is not true.

I saw that you had a commit to fix the memory leak here https://github.com/duckietown/lib-dt-apriltags/commit/deb4c37327de2aa81a941448d5f2e6bbbf49351e

However, I still got the segmentation fault. but the error did not consistently happen all the time.
I am using v3.1.7.

**Comment by xmba15** [comment]
just found out about this https://github.com/duckietown/lib-dt-apriltags/issues/20
Sorry this might be a duplicate issue. but the issue might not have been solved yet.

**Comment by afdaniele** [comment]
The memory leak is fixed but the segmentation fault is still there. Unfortunately it doesn't bother us in Duckietown too much, at least not enough to make it into the TODO list.

**Comment by xmba15** [comment]
@afdaniele Thank you for the confirmation. Maybe I will dig into it when I have time. If I find anything, I will come back later.
I will close the issue then.
