### ISSUE TITLE
How to obtain the camera calibration parameters

### ISSUE THREAD

**Issue by swapnilsayansaha** [duckietown/lib-dt-apriltags#4]
It's not really an issue, but I was wondering how one would obtain the camera calibration params provided in the yaml file.

**Comment by AleksandarPetrov** [comment]
Do you mean in `test_info.yaml`? With this: https://github.com/duckietown/lib-dt-apriltags/blob/3f8fb9f8d53aa369481534b7b13148905bd019a3/test/test.py#L33-L34

**Comment by swapnilsayansaha** [comment]
Yes. I did figure out later though. I used MATLAB's camera calibrator to find the camera parameters. Thanks.

**Comment by pra-dan** [comment]
[This article](https://www.orangenarwhals.com/2018/04/getting-started-with-apriltags-on-ubuntu-16-04/) beautifully explains it. :smile:

**Comment by hakanErgin** [comment]
Sorry for bumping this.

> [This article](https://www.orangenarwhals.com/2018/04/getting-started-with-apriltags-on-ubuntu-16-04/) beautifully explains it. 😄

I was just curious, if you have an opinion, what would be the difference between using a checkers board or actual an apriltags board to make the calibration ( [for example](https://www.mathworks.com/help/vision/ug/camera-calibration-using-apriltag-markers.html) )?

cheers
